version: '3.7'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123123
    ports:
      - '35432:5432'

  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: ts-node-docker
    expose:
      - '3000'
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      - POSTGRES_URI=postgres://postgres:123123123@postgres:5432
      - FAILED_RATE_RANDOM=0.3
      - BANK_ACC=acc1234
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; node dist/cjs/index.js'

